services:
  - type: web
    name: seniqu-backend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
